src/Entity/Abonnement.php
<?php

namespace App\Entity;

use App\Repository\AbonnementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AbonnementRepository::class)]
class Abonnement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'abonnements')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'abonnements')]
    private ?Categorie $categorie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_expiration = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getDateExpiration(): ?\DateTimeInterface
    {
        return $this->date_expiration;
    }

    public function setDateExpiration(?\DateTimeInterface $date_expiration): static
    {
        $this->date_expiration = $date_expiration;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }




}

src/Form/AbonnementType.php
<?php

namespace App\Form;

use App\Entity\Abonnement;
use App\Entity\Adherant;
use App\Entity\Categorie; // Make sure to include the correct namespace
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AbonnementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type')
            ->add('date_expiration', DateType::class, [
                'widget' => 'single_text',
                // add any other DateType options you need
            ])
            ->add('date_debut', DateType::class, [
                'widget' => 'single_text',
                // add any other DateType options you need
            ])
            ->add('prix', NumberType::class, [
                'scale' => 2, // add this option if you want to allow decimal places
            ])
            ->add('user', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'email',
                //'choice_label' => function($user){
                //  return $user ->getPrenom() . ' ' . $user ->getNom();}
                //,
                "expanded" =>false,
                "multiple" =>false

            ])
            ->add('categories', EntityType::class, [
                'class' => Categorie::class,
                'choice_label' => 'nom_categorie',
                "expanded" =>false,
                'multiple' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Abonnement::class,
        ]);
    }
}

src/Controller/AbonnementController.php
<?php

namespace App\Controller;

use App\Entity\Abonnement;
use App\Form\AbonnementType;
use App\Repository\AbonnementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/abonnement')]
class AbonnementController extends AbstractController
{
    #[Route('/', name: 'app_abonnement_index', methods: ['GET'])]
    public function index(AbonnementRepository $abonnementRepository): Response
    {
        return $this->render('abonnement/index.html.twig', [
            'abonnements' => $abonnementRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_abonnement_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $abonnement = new Abonnement();
        $form = $this->createForm(AbonnementType::class, $abonnement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($abonnement);
            $entityManager->flush();

            return $this->redirectToRoute('app_abonnement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('abonnement/new.html.twig', [
            'abonnement' => $abonnement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_abonnement_show', methods: ['GET'])]
    public function show(Abonnement $abonnement): Response
    {
        return $this->render('abonnement/show.html.twig', [
            'abonnement' => $abonnement,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_abonnement_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Abonnement $abonnement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AbonnementType::class, $abonnement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_abonnement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('abonnement/edit.html.twig', [
            'abonnement' => $abonnement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_abonnement_delete', methods: ['POST'])]
    public function delete(Request $request, Abonnement $abonnement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$abonnement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($abonnement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_abonnement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/abonnement/_delete_form.html.twig
<form method="post" action="{{ path('app_abonnement_delete', {'id': abonnement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ abonnement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/abonnement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Abonnement{% endblock %}

{% block body %}
    <h1>Edit Abonnement</h1>

    {{ include('abonnement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_abonnement_index') }}">back to list</a>

    {{ include('abonnement/_delete_form.html.twig') }}
{% endblock %}

templates/abonnement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Abonnement{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset("index_adherant.css") }}">
{% endblock %}

{% block body %}
<div class="wrapper">
    <header class="navbar">
        <a href="{{ path('app_adherant_new') }}" class="logo">
            <img src="{{ asset("images/logo.png") }}" alt="Your Logo">
        </a>
        <nav class="nav-links">
            <a href="{{ path('app_adherant_new') }}">Home</a>
            <a href="{{ path('app_adherant_new') }}">About</a>
            <a href="{{ path('app_adherant_new') }}">Contact</a>
        </nav>
    </header>

    <div class="card-container">
        <div class="card">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Type</th>
                <th>Date_expiration</th>
                <th>Date_debut</th>
                <th>Prix</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for abonnement in abonnements %}
            <tr>
                <td>{{ abonnement.id }}</td>
                <td>{{ abonnement.type }}</td>
                <td>{{ abonnement.dateExpiration ? abonnement.dateExpiration|date('Y-m-d') : '' }}</td>
                <td>{{ abonnement.dateDebut ? abonnement.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ abonnement.prix }}</td>
                <td>
                    <a href="{{ path('app_abonnement_show', {'id': abonnement.id}) }}">show</a>
                    <a href="{{ path('app_abonnement_edit', {'id': abonnement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
            <a href="{{ path('app_abonnement_new') }}" class="create-link">Create New </a>
        </div>
    </div>
</div>
    <footer class="footer">
        <p>&copy; 2023 Your Company. All rights reserved.</p>
    </footer>
{% endblock %}

templates/abonnement/new.html.twig
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <title>Ajouter Abonnement</title>
    <link rel="stylesheet" href="{{ asset("addabonnement.css") }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="container">
    <div class="title">Nouvel Abonnement</div>
    <div class="content">
        {{ form_start(form) }}
        <div class="user-details">
            <div class="input-box">
                {{ form_label(form.type, 'Type') }}
                {{ form_widget(form.type) }}
            </div>
            <div class="input-box adherant-input">
                {{ form_label(form.adherant, 'Adherent') }}
                {{ form_widget(form.adherant) }}
            </div>
            <div class="input-box date-input">
                {{ form_label(form.date_expiration, 'Date d\'expiration') }}
                {{ form_widget(form.date_expiration) }}
            </div>
            <div class="input-box date-input">
                {{ form_label(form.date_debut, 'Date de début') }}
                {{ form_widget(form.date_debut) }}
            </div>
            <div class="input-box categories-input">
                {{ form_label(form.categories, 'Categories') }}
                {{ form_widget(form.categories) }}
            </div>
            <div class="input-box">
                {{ form_label(form.prix, 'Prix') }}
                {{ form_widget(form.prix) }}
            </div>
        </div>
        <div class="button">
            <input type="submit" value="Enregistrer">
        </div>
        {{ form_end(form) }}
    </div>
</div>
</body>
</html>

templates/abonnement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Abonnement{% endblock %}

{% block body %}
    <h1>Abonnement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ abonnement.id }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ abonnement.type }}</td>
            </tr>
            <tr>
                <th>Date_expiration</th>
                <td>{{ abonnement.dateExpiration ? abonnement.dateExpiration|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ abonnement.dateDebut ? abonnement.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ abonnement.prix }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_abonnement_index') }}">back to list</a>

    <a href="{{ path('app_abonnement_edit', {'id': abonnement.id}) }}">edit</a>

    {{ include('abonnement/_delete_form.html.twig') }}
{% endblock %}